### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by kybe236** [Lokfid/RusherWebPlugin#6]
This happens as soon as i open the window

```
[21:30:47] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:922) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1285) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoSuchMethodError: 'void org.rusherhack.client.api.render.IRenderer2D._drawTextureRectangle(int, int, int, double, double, double, double, double)'
	at org.lokfid.BrowserWindowView.renderContent(BrowserWindowView.java:101) ~[?:?]
	at org.rusherhack.client.api.ui.window.WindowContentHandlerBase.handleRenderContent(WindowContentHandlerBase.java:36) ~[?:?]
	at org.rusherhack.Ǔ.handleRenderContent(Ǔ.java:766) ~[?:?]
	at org.rusherhack.Ѐ.handleRenderViewContent(Ѐ.java:647) ~[?:?]
	at org.rusherhack.client.api.ui.window.view.WindowView.renderContent(WindowView.java:63) ~[?:?]
	at org.rusherhack.client.api.ui.window.WindowContentHandlerBase.handleRenderContent(WindowContentHandlerBase.java:36) ~[?:?]
	at org.rusherhack.Ǔ.handleRenderContent(Ǔ.java:766) ~[?:?]
	at org.rusherhack.client.api.ui.window.view.SimpleView.renderViewContent(SimpleView.java:62) ~[?:?]
	at org.rusherhack.client.api.ui.window.WindowViewHandlerBase.handleRenderViewContent(WindowViewHandlerBase.java:28) ~[?:?]
	at org.rusherhack.Ѐ.handleRenderViewContent(Ѐ.java:685) ~[?:?]
	at org.rusherhack.client.api.ui.window.view.WindowView.renderContent(WindowView.java:63) ~[?:?]
	at org.rusherhack.client.api.ui.window.WindowContentHandlerBase.handleRenderContent(WindowContentHandlerBase.java:36) ~[?:?]
	at org.rusherhack.Ǔ.handleRenderContent(Ǔ.java:766) ~[?:?]
	at org.rusherhack.client.api.ui.window.WindowHandlerBase.renderWindow(WindowHandlerBase.java:123) ~[?:?]
	at org.rusherhack.ȃ.renderWindow(ȃ.java:219) ~[?:?]
	at org.rusherhack.client.api.ui.window.WindowHandlerBase.renderElements(WindowHandlerBase.java:86) ~[?:?]
	at org.rusherhack.ȃ.renderElements(ȃ.java:146) ~[?:?]
	at org.rusherhack.client.api.ui.ElementHandlerBase.render(ElementHandlerBase.java:99) ~[?:?]
	at org.rusherhack.client.Ψ.method_25394(Ψ.java:39) ~[?:?]
	at net.minecraft.class_437.method_47413(class_437.java:117) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.mixinextras$bridge$method_47413$221(class_757.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.wrapOperation$znc000$fabric-screen-api-v1$onRenderScreen(class_757.java:2086) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:913) ~[client-intermediary.jar:?]
	... 12 more
	```

**Comment by Lokfid** [comment]
can you please try the new version for 1.20.4 and tell if that still happens

**Comment by Lokfid** [comment]
Confirmed via discord
